POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Oliver Robie",
    "number": "123-456789"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "123-456789"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Oliver Robie"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Oliver Robie",
    "number": "489-3571290"
}
